import { state, cfg, INIT_ROWS, getArrangementDataForSave } from './state.js';
import { initSeats, updateSelectLogic, onSeatCountChange, onColCountChange, onLayoutChange, onAlgoChange } from './layout.js';
import { renderSeats, updateBadge, toggleTeacherView, executeArrangement } from './view.js';
import { downloadTemplate, loadStudentExcel, exportToExcel, saveAsImage, printScreen, saveFile, loadFile, onLoadFile, addStudentRow, initGrid, processLoadedData } from './io.js';
import { toast, showConfirm, confirmOk, confirmCancel, updateStudentListPreview, openStudentModal, closeStudentModal, toggleSaveMenu, hideSaveMenu } from './ui.js';

window.getArrangementDataForSave = getArrangementDataForSave;
window.onSeatCountChange = () => { onSeatCountChange(); renderSeats(); updateBadge(); };
window.onColCountChange = () => { onColCountChange(); renderSeats(); updateBadge(); };
window.onLayoutChange = () => { onLayoutChange(); renderSeats(); updateBadge(); };
window.onAlgoChange = onAlgoChange;
window.toggleTeacherView = toggleTeacherView;
window.downloadTemplate = downloadTemplate;
window.loadStudentExcel = loadStudentExcel;
window.exportToExcel = exportToExcel;
window.saveAsImage = saveAsImage;
window.printScreen = printScreen;
window.saveFile = saveFile;
window.loadFile = loadFile;
window.onLoadFile = onLoadFile;
window.openStudentModal = openStudentModal;
window.closeStudentModal = closeStudentModal;
window.toggleSaveMenu = toggleSaveMenu;
window.hideSaveMenu = hideSaveMenu;
window.showConfirm = showConfirm;
window.confirmOk = confirmOk;
window.confirmCancel = confirmCancel;
window.executeArrangement = executeArrangement;
window.addStudentRow = addStudentRow;
window.processLoadedData = processLoadedData;

initGrid(INIT_ROWS);
updateSelectLogic();
initSeats();
updateBadge();
renderSeats();
updateStudentListPreview();
document.documentElement.style.setProperty('--seat-font', cfg.fontFamily);
